### ISSUE TITLE
Example 5.4 is questionable - requires at least proper definition

### ISSUE THREAD

**Issue by DDvO** [lamps-wg/lamps-rfc7030-csrattrs#45]
@danharkins @mcr this example is about providing a CSR with an RSA key with 4096 bits size.
Its encoding pretends/assumes that the AlgorithmIdentifier with OID `rsaEncryption` had a parameter specifying the key length.
Yet such a parameter is not really defined for RSA. 
In RFC 9483 we solved this by introducing the `rsaKeyLen` OID: https://datatracker.ietf.org/doc/html/rfc9483#section-4.3.3

It may be okay to use instead the encoding already given for the example:
```
    13  17:   SEQUENCE {
       <06 09>
    15   9:     OBJECT IDENTIFIER rsaEncryption (1 2 840 113549 1 1 1)
          :       (PKCS #1)
       <31 04>
    26   4:     SET {
       <02 02>
    28   2:       INTEGER 4096
          :       }
          :     }
```
but only if this is explicitly defined in general terms in section 3.2.

**Comment by mcr** [comment]
Should we just drop this example?

**Comment by mcr** [comment]
@DDvO I think this is fixed now, closing.  reopen if you disagree.

**Comment by DDvO** [comment]
Also here, pretending that the newly created issue disappeared does not solve it.

**Comment by DDvO** [comment]
> Should we just drop this example?

I'm for keeping the example because specifying an RSA key of a given size is a valid and presumably even typical use case.

To solve the issue, it should be sufficient to add at the end of section 3.2 something like this:

When not using the template-based approach of {#csrtemplate}, specifying the requirement for a public key of a specific type and optionally its size and other parameters MUST be done as follows. Include exactly one Attribute with the '`type`' field being the OID specifying the type of the key, such as `ecPublicKey` or `rsaEncryption`. The '`values`' field MAY be empty to indicate no further requirements on the key. Otherwise it MUST contain suitable parameters for the given key type, such as a singleton set containing the OID of an EC curve such as `secp384r1` or containing an integer value for the RSA key size such as 4096.
Many examples for this are given in Section 5.

**Comment by DDvO** [comment]
This has been fixed today with version 18.
